# Installs dependencies for YOLACT managed by Anaconda. 
# Advantage is you get working CUDA+cuDNN+pytorch+torchvison versions.
#
# TODO: you must additionally install nVidia drivers, eg. on Ubuntu linux 
# `apt install nvidia-driver-440` (change the 440 for whatever version you need/have).
#
name: yolact-env
#prefix: /your/custom/path/envs/yolact-env
channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - pip
  - python=3.10
  - pytorch=1.13.1
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - matplotlib

  - curl # to download COCO dataset
  # - unzip # to download COCO dataset
  - pip:
    - opencv-python 
    - opencv-contrib-python
    - opencv-python-headless
    - pillow <7.0 # bug PILLOW_VERSION in torchvision, must be < 7.0 until torchvision is upgraded
    - pycocotools 
    - PyQt5 # needed on KDE/Qt envs for matplotlib

